name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
 GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: '1.24.x'

      - name: Ensure dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          install-go: false
          version: "latest"

      - name: Vet
        run: |
          go vet ./...

      - name: Run tests
        run: |
          go test -mod vendor -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release-please:
    if: ${{ github.event_name != 'pull_request'}}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.BOT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: go

  automerge:
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Automerge dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
