name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  GO111MODULE: on

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: "1.24.x"

      - name: Lint
        uses: golangci/golangci-lint-action@v8

  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'networkguild-bot[bot]' || !contains(github.event.pull_request.title, 'release') }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: "1.24.x"

      - name: Ensure dependencies
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: Run tests
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    if: ${{ github.event_name != 'pull_request'}}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.BOT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          skip-github-pull-request: true

  release-pr:
    if: ${{ github.event_name != 'pull_request'}}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.BOT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          skip-github-release: true

  automerge:
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.BOT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Automerge dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
          github-token: ${{ steps.app-token.outputs.token }}
          use-github-auto-merge: true
