name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
 GO111MODULE: on

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: '1.24.x'

      - name: Lint
        uses: golangci/golangci-lint-action@v7

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: '1.24.x'

      - name: Ensure dependencies
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: Run tests
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  automerge:
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Automerge dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
